### ISSUE TITLE
Singular.jl Development Roadmap

### ISSUE THREAD

**Issue by wbhart** [wbhart/Singular.jl#22]
Singular wrappers of Nemo coefficient rings
- [ ] Efficient nmod coefficient ring using UInt's as numbers and calling Flint directly using ccall
- [ ] Efficient GF(p) coefficient field, as per the nmod coefficient ring
- [ ] Efficient Zech log coefficient field using UInt's for the field elements
